#!/bin/bash

# Обновляем пакеты
sudo apt update && sudo apt upgrade -y

# Запускаем Apache2 и добавляем в автозагрузку
sudo systemctl start apache2
sudo systemctl enable apache2

# Устанавливаем правильные права
sudo chown -R www-data:www-data /var/www/html
sudo chmod -R 755 /var/www/html

# Проверяем статус Apache2
sudo systemctl status apache2
